### ISSUE TITLE
Split sources into repositories

### ISSUE THREAD

**Issue by Vanuan** [pocketbook-free/pocketbook_free#3]
Maybe it is more appropriate to setup different repo for each project?

**Comment by pocketbook-free** [comment]
Please tell why is it necessary to split to separate repositaries?

**Comment by Vanuan** [comment]
There are several advantages.
When you split repositories, you can import upstream projects and rebase your changes on top of the latest revision. It's easier to review changes and submit them. And you'll always have the latest revision and updating would be very easy.
Also you could work on one project at a time, updating them independently. So you don't have to download all the source code which is heavy, only parts you're interested in. Also it will be faster, because git doesn't handle large projects very well.

To download all projects to your machine Android project use a repo tool (http://source.android.com/source/version-control.html). But I think git submodules would be fine.

Official mirror of linux source code is here, on github https://github.com/torvalds/linux
Webkit: git://git.webkit.org/WebKit.git
Poppler: git://git.freedesktop.org/git/poppler/poppler 
FBReader: https://github.com/geometer/FBReaderJ
And so on.

**Comment by Vanuan** [comment]
Different devices probably use different versions of software. So one project should be set up for every device.

I could easily setup all the repos if I knew which versions was the basis of your modifications.

**Comment by Vanuan** [comment]
Moreover, do you have any plans how would you make your sources up-to-date?
If you're using svn, there's a tool git-svn to make your life easier.
Maybe you could even switch to git as your main version control system?

**Comment by Vanuan** [comment]
As an example you can see how it's organized in OpenInkpot: http://git.openinkpot.org/
